

# =========================================
# 장소별 객체 가중치
# 점수는 필요하면 계속 조정하면 됩니다.
# =========================================
PLACE_WEIGHTS = {
    "cafe": {
        "cup": 4,
        "wine glass": 3,
        "bottle": 2,
        "chair": 2,
        "dining table": 4,
        "fork": 1,
        "knife": 1,
        "spoon": 1,
        "bowl": 1,
        "pizza": 2,
        "person": 3,
        "cake": 2,
    },
    "restaurant": {
        "chair": 3,
        "dining table": 4,
        "cup": 2,
        "wine glass": 2,
        "fork": 2,
        "knife": 2,
        "spoon": 2,
        "bowl": 2,
        "pizza": 2,
        "cake": 1,
    },
    "office": {
        "person": 1,
        "chair": 3,
        "laptop": 4,
        "keyboard": 4,
        "mouse": 4,
        "cell phone": 2,
        "tv": 1,
        "clock": 2,
        "book": 1,
        "potted plant": 1,
    },
    "classroom": {
        "person": 2,
        "chair": 3,
        "backpack": 4,
        "book": 4,
        "laptop": 2,
        "tv": 1,
        "clock": 2,
        "cell phone": 1,
        "bottle": 1,
    },
    "park": {
        "person": 2,
        "bench": 4,
        "dog": 3,
        "umbrella": 2,
        "kite": 2,
        "frisbee": 2,
        "sports ball": 1,
        "bicycle": 2,
        "skateboard": 1,
    },
    "street": {
        "person": 1,
        "car": 4,
        "bus": 4,
        "truck": 3,
        "motorcycle": 2,
        "traffic light": 4,
        "stop sign": 4,
        "bicycle": 2,
    },
    "kitchen": {
        "bottle": 2,
        "cup": 2,
        "bowl": 3,
        "fork": 2,
        "knife": 2,
        "spoon": 2,
        "banana": 1,
        "apple": 1,
        "orange": 1,
        "microwave": 4,
        "oven": 4,
        "toaster": 4,
        "sink": 4,
        "refrigerator": 4,
    },
    "living_room": {
        "person": 1,
        "couch": 5,
        "chair": 2,
        "tv": 4,
        "remote": 3,
        "potted plant": 2,
        "clock": 1,
        "book": 1,
    },
    "bedroom": {
        "bed": 5,
        "potted plant": 1,
        "tv": 2,
        "book": 1,
        "clock": 1,
        "chair": 1,
        "laptop": 1,
    },
    "bathroom": {
        "toilet": 5,
        "sink": 4,
        "toothbrush": 2,
        "person": 1,
        "bottle": 1,
    },
    "beach": {
        "person": 2,
        "umbrella": 4,
        "boat": 3,
        "surfboard": 5,
        "kite": 2,
        "bottle": 1,
        "chair": 1,
    },
    "airport": {
        "airplane": 5,
        "suitcase": 4,
        "backpack": 3,
        "person": 5,
        "bench": 2,
        "chair": 1,
        "clock": 1,
        "tv": 1,
    },
    "zoo": {
        "elephant": 4,
        "giraffe": 4,
        "zebra": 4,
        "bear": 4,
        "bird": 3,
        "dog": 2,
        "horse": 2,
    },
}
